// Country code to full name and flag mapping
export const countryData: Record<string, { name: string; flag: string }> = {
  'US': { name: 'United States', flag: '🇺🇸' },
  'GB': { name: 'United Kingdom', flag: '🇬🇧' },
  'CA': { name: 'Canada', flag: '🇨🇦' },
  'AU': { name: 'Australia', flag: '🇦🇺' },
  'DE': { name: 'Germany', flag: '🇩🇪' },
  'FR': { name: 'France', flag: '🇫🇷' },
  'IT': { name: 'Italy', flag: '🇮🇹' },
  'ES': { name: 'Spain', flag: '🇪🇸' },
  'NL': { name: 'Netherlands', flag: '🇳🇱' },
  'BE': { name: 'Belgium', flag: '🇧🇪' },
  'CH': { name: 'Switzerland', flag: '🇨🇭' },
  'AT': { name: 'Austria', flag: '🇦🇹' },
  'SE': { name: 'Sweden', flag: '🇸🇪' },
  'NO': { name: 'Norway', flag: '🇳🇴' },
  'DK': { name: 'Denmark', flag: '🇩🇰' },
  'FI': { name: 'Finland', flag: '🇫🇮' },
  'PL': { name: 'Poland', flag: '🇵🇱' },
  'CZ': { name: 'Czech Republic', flag: '🇨🇿' },
  'RO': { name: 'Romania', flag: '🇷🇴' },
  'HU': { name: 'Hungary', flag: '🇭🇺' },
  'GR': { name: 'Greece', flag: '🇬🇷' },
  'PT': { name: 'Portugal', flag: '🇵🇹' },
  'IE': { name: 'Ireland', flag: '🇮🇪' },
  'RU': { name: 'Russia', flag: '🇷🇺' },
  'UA': { name: 'Ukraine', flag: '🇺🇦' },
  'TR': { name: 'Turkey', flag: '🇹🇷' },
  'IL': { name: 'Israel', flag: '🇮🇱' },
  'SA': { name: 'Saudi Arabia', flag: '🇸🇦' },
  'AE': { name: 'United Arab Emirates', flag: '🇦🇪' },
  'IN': { name: 'India', flag: '🇮🇳' },
  'CN': { name: 'China', flag: '🇨🇳' },
  'JP': { name: 'Japan', flag: '🇯🇵' },
  'KR': { name: 'South Korea', flag: '🇰🇷' },
  'TW': { name: 'Taiwan', flag: '🇹🇼' },
  'HK': { name: 'Hong Kong', flag: '🇭🇰' },
  'SG': { name: 'Singapore', flag: '🇸🇬' },
  'MY': { name: 'Malaysia', flag: '🇲🇾' },
  'TH': { name: 'Thailand', flag: '🇹🇭' },
  'VN': { name: 'Vietnam', flag: '🇻🇳' },
  'PH': { name: 'Philippines', flag: '🇵🇭' },
  'ID': { name: 'Indonesia', flag: '🇮🇩' },
  'BD': { name: 'Bangladesh', flag: '🇧🇩' },
  'LK': { name: 'Sri Lanka', flag: '🇱🇰' },
  'BR': { name: 'Brazil', flag: '🇧🇷' },
  'MX': { name: 'Mexico', flag: '🇲🇽' },
  'AR': { name: 'Argentina', flag: '🇦🇷' },
  'CL': { name: 'Chile', flag: '🇨🇱' },
  'CO': { name: 'Colombia', flag: '🇨🇴' },
  'PE': { name: 'Peru', flag: '🇵🇪' },
  'VE': { name: 'Venezuela', flag: '🇻🇪' },
  'CU': { name: 'Cuba', flag: '🇨🇺' },
  'ZA': { name: 'South Africa', flag: '🇿🇦' },
  'EG': { name: 'Egypt', flag: '🇪🇬' },
  'NG': { name: 'Nigeria', flag: '🇳🇬' },
  'KE': { name: 'Kenya', flag: '🇰🇪' },
  'NZ': { name: 'New Zealand', flag: '🇳🇿' },
}

export function getCountryInfo(code: string | undefined): { name: string; flag: string } | null {
  if (!code) return null
  const upperCode = code.toUpperCase()
  return countryData[upperCode] || { name: code, flag: '🌍' }
}
